### ISSUE TITLE
Missing checks for node tree constraints?

### ISSUE THREAD

**Issue by Ms2ger** [jsdom/jsdom#1349]
https://github.com/tmpvar/jsdom/blob/28f00b30236d540df1777ca6c2c0ee9e5e19fe5b/test/web-platform-tests/to-upstream/dom/nodes/Node-isEqualNode.html tries to append a doctype to a comment. This is supposed to throw.

**Comment by domenic** [comment]
For anyone looking to tackle this, it consists of:

- Implementing https://dom.spec.whatwg.org/#concept-node-ensure-pre-insertion-validity
- Hooking it up to the appropriate call sites, which right now do their own ad-hoc checking I believe
- Fixing any broken tests we wrote, like the one @Ms2ger cites
- Enabling any WPTs that are currently disabled under dom/nodes because we fail to implement this
- Judging whether the newly-enabled tests give enough coverage, or whether we need to write more
