### ISSUE TITLE
Make Attr inherit from Node again

### ISSUE THREAD

**Issue by brettz9** [jsdom/jsdom#1641]
The inheritance of `Attr` from `Node` was [added back](https://github.com/whatwg/dom/issues/102). Please support (although `nodeName` exists as an alias, `nodeType` is not available, etc.).

**Comment by snuggs** [comment]
@domenic anyone working on this? If not can take a 🔪 at it.

**Comment by Robbert** [comment]
Last weekend I really needed `Attr` as `Node` again, and my attempted to do some refactoring turned out largely successful:
https://github.com/Robbert/jsdom/commits/issue-1641

I expect more work needs to be done to fully support `Attr` everywhere, in `TreeWalker` for example, I guess I should use annevk's commits to the DOM standard as checklist.

The main difficulty was the cyclic dependency of Node ⇒ attributes.js ⇒ Attr ⇒ Node, I noticed domenic ran into this issue earlier (https://github.com/tmpvar/jsdom/pull/1247#issuecomment-149060470). Since any type of `Node` usually is created through the `Document`, I chose to follow this pattern to remove the direct dependency of `attibutes.js` on `Attr`, and instead `Attr` is created through the `ownerDocument` of the `ownerElement` of the `NamedNodeMap`. This way no direct dependency on `Attr` is required.

Also, I'm registering all `Node` constructors on the `Document` implementation in a similar fashion as the custom element constructors for the HTML DOM are registered. In another DOM implementation I worked on previously this approach worked splendidly.

If someone has time to give their opinion on this approach sometime, I can process the feedback and after that finish up details like `TreeWalker` support and updating the tests.

**Comment by snuggs** [comment]
1. @Robbert any way we can get this in a PR on your fork? Difficult to see the diffs.
2. Can you rebase the branch to reflect recent changes? Also will help with visibility.
Looking good but need to pull down branch to diff. I know there are ways in github but just too lazy. 😁  Still should do 1, and 2 tho.

Please advise.

**Comment by Robbert** [comment]
@snuggs Definitely, wasn't sure if it was appropriate to send a pull request for work in progress. Will do so this week.

**Comment by chiptus** [comment]
any update on this? is it still in progress? or should I try to take it?

**Comment by chiptus** [comment]
is there any other node that will return nodeType undefined?

**Comment by Robbert** [comment]
@snuggs I just sent the pull request for my branch, sorry it took so long. This week I have plenty of time to look into the failing unit tests, but I prefer to only spend more time on this when the approach I took is acceptable.
