### ISSUE TITLE
use of `:required:` selector causes exception

### ISSUE THREAD

**Issue by subyraman** [jsdom/jsdom#1955]
### Basic info:

- **Node.js version:** 6.11.2
- **jsdom version:** 11.2.0

### Minimal reproduction case

https://runkit.com/embed/b6i65elcwx8d

```js
const jsdom = require("jsdom");
const dom = new jsdom.JSDOM('<input required disabled name="foo" />');
dom.window.document.querySelectorAll(':required')
```

### How does similar code behave in browsers?

Works correctly in a browser environment:

https://codepen.io/anon/pen/QMrYXW

**Comment by Zirro** [comment]
It looks like the current version of [nwmatcher](https://github.com/dperini/nwmatcher) requires an [extension](https://github.com/dperini/nwmatcher/blob/master/src/modules/nwmatcher-webforms.js) in order to support these pseudo selectors.

However, there seems to be a significant update to nwmatcher coming as a new package, which [includes](https://github.com/dperini/nwsapi/commit/9e598d4a62950bca314e8ad63a32c136c6faeb1a) support for these selectors by default. It's not been released on npm yet, though. @dperini, how goes your work on nwsapi?

**Comment by dperini** [comment]
@Zirro,
yes I am working on "nwsapi" which is the WIP for the forthcoming "nwmatcher-2.x" code.
The objective is getting most of Level 4 compliance regarding the recognized selectors.
However most of the work done lately is about performances and code reorganization.

The speed improvements are amazing ... have to be seen to believe :)
It is currently faster than any browser in any area (2x-4x), including structural pseudo-classes.

I am missing some testing suite for the Level 4 selectors, especially for the ":scope" pseudo-class". Do you have links to some test or can you point me in the right place ?

**Comment by Zirro** [comment]
If you can run web-platform-tests, these seem to cover the web-forms selectors pretty well: https://github.com/w3c/web-platform-tests/tree/master/html/semantics/selectors/pseudo-classes

Unfortunately I was not able to find one for `:scope` in querySelector().

> It is currently faster than any browser in any area (2x-4x), including structural pseudo-classes.

That sounds amazing! I look forward to seeing it used in jsdom :-)

**Comment by Zirro** [comment]
This selector is supported now and is tested by https://github.com/web-platform-tests/wpt/blob/master/html/semantics/selectors/pseudo-classes/required-optional.html.
