### ISSUE TITLE
Upgrade from content-type-parser to whatwg-mimetype

### ISSUE THREAD

**Issue by domenic** [jsdom/jsdom#2078]
Just released this: https://www.npmjs.com/package/whatwg-mimetype

It complies with the latest MIME Sniffing Standard, yay. It'll help us pass more tests, likely.

**Comment by gaearon** [comment]
Sorry for hijacking this thread, but is there any chance the deprecation warning could be removed until jsdom has been updated?

We indirectly depend on this package from Create React App, a tool that is overwhelmingly used by beginners who are completely new to the npm ecosystem. All of them will see a scary deprecation warning now every time they create a project, and it is not actionable for them.

Seeing such warnings makes people doubt themselves, and eventually trains them to ignore any warnings altogether. We’ve been trying to reduce any such noise in our project and we’d really appreciate if it was possible to first release a jsdom update and then provide a grace period (e.g. a month) to get it integrated before showing the deprecation message.

Thanks for reading! Our downstream issue: https://github.com/facebookincubator/create-react-app/issues/3586

**Comment by StephenLynx** [comment]
@gaearon It is a really practice to just squelch warnings ever. They are there for a reason.

**Comment by domenic** [comment]
@gaearon I've un-deprecated it for now, as indeed it doesn't make much sense when there's no version of jsdom that uses the replacement. I don't think we'll have much of a grace period, but at least it will remain un-deprecated until a jsdom release is available that includes the right package, and since jest-environment-jsdom uses `^` dependency syntax, that should be good enough.

**Comment by gaearon** [comment]
Thanks, this is very much appreciated!

**Comment by nickmccurdy** [comment]
There is now a medium severity [Regular Expression Denial of Service](https://snyk.io/vuln/npm:content-type-parser:20170905) reported by Snyk for `content-type-parser` that is fixed in `whatwg-mimetype`. I'm looking into making this change in jsdom.

**Comment by domenic** [comment]
As noted in https://github.com/jsdom/whatwg-mimetype/issues/3, that isn't an issue for jsdom, which isn't usable on untrusted input anyway.

**Comment by nickmccurdy** [comment]
Thanks, that's good to know. I already started though, so I'll keep working on this for maintenance purposes. Then maybe we could reintroduce the deprecation warning after `jsdom`, `create-react-app`, and the intermediate dependencies get updated.

**Comment by domenic** [comment]
I mean, https://github.com/tmpvar/jsdom/pull/2079 already exists, I just need to find the time to merge it.

**Comment by domenic** [comment]
Fixed by https://github.com/jsdom/jsdom/commit/d5639655d32d45b6690c9ac30901136e650eb99a

**Comment by mackermans** [comment]
@domenic Could you release a new version which includes this fix? Snyk.io is reporting `content-type-parser` as medium vulnerability in our project because of the ReDoS possibility, while the only related dependency is six links away:

```lint-staged@7.0.0 › jest-validate@22.4.2 › jest-config@22.4.2 › jest-environment-jsdom@22.4.1 › jsdom@11.6.2 › content-type-parser@1.0.2```

Releasing a new version would trigger a lot of packages to update `jsdom` and finally get rid of this alert.

**Comment by mackermans** [comment]
@domenic Could you release a new version containing https://github.com/jsdom/jsdom/commit/d5639655d32d45b6690c9ac30901136e650eb99a? So that packages can start updating their version of `jsdom`, since `jsdom@11.6.2` still contains `content-type-parser@1.0.2`, which is reported as vulnerable in Snyk.io.

**Comment by domenic** [comment]
That tool is faulty then, as jsdom is not safe to run on untrusted input anyway, so this change has no impact on security. I am actively against supporting such faulty tools as they have been very annoying to me as a maintainer.

**Comment by mackermans** [comment]
@domenic I understand, however the problem is not necessarily `jsdom` right now but `content-type-parser`, apparently getting rid of that package mitigates the issue. And since you have already replaced it with `whatwg-mimetype`, releasing a new version would seem like a trivial solution.

As for Snyk, you're right in that it is probably too naive in detecting vulnerabilities, but it has still proven to be of value at the company I work at. We prefer to keep using it (or at least until we find a better vulnerability detection tool).

Anyway, I get your point, so no hard feelings if you decide not to release a new version. We can find some workaround 🙂

**Comment by bunchito** [comment]
@mackermans 
Did you find a workaround? Will appreciate any kind of help or advice.

**Comment by mackermans** [comment]
@bunchito Since `whatwg-mimetype` has replaced `content-type-parser` since `jsdom@11.7.0`, this is no longer an issue for us. Simply updating `jsdom` should solve it for you too.
