### ISSUE TITLE
[readme] Question about § Pretending to be a visual browser

### ISSUE THREAD

**Issue by tigt** [jsdom/jsdom#2205]
Specifically:

> * Changing `document.hidden` to return `true` instead of `false`

Shouldn't it be the other way around, or am I missing something? A visible page would be `document.hidden == false`, I thought…

**Comment by domenic** [comment]
Good catch! PR welcome.

**Comment by kapouer** [comment]
That rang a bell ! Make sure anything you do is in line with visiblity api...
https://github.com/jsdom/jsdom/blob/b0ca4dda876ff63aa535da98fd984c33caee026b/lib/jsdom/living/nodes/Document-impl.js#L816-L823
shows how to take into account to "pretending" thing.

**Comment by kapouer** [comment]
Thinking of which i realize "hidden" and "visibilityState" implementations are not bound together.
They should be ?
[Documentation](https://w3c.github.io/page-visibility/) says
`Document.hidden is historical. Use Document.visibilityState instead.`
However, compatibility behavior basically says (and here i interpret): `return visibilityState`.
This works because what `document.hidden` is supposed to return is a *string*, not a boolean.

**Comment by kapouer** [comment]
Right, i overlooked that part:
```
get hidden() {
  return this.visibilityState == "visible";
}
```
should fix it.

**Comment by kapouer** [comment]
@Zirro @domenic any comment ?

**Comment by Zirro** [comment]
@kapouer We'd appreciate if you don't ping us unless there's a critical issue, or several weeks have gone by. This is a spare time project for us, and we're already watching the repository to receive notifications about every issue, pull request and comment.

This issue is only about the [README.md](https://github.com/jsdom/jsdom/blame/master/README.md#L112) file and not the code itself.
