### ISSUE TITLE
Support `Performance`

### ISSUE THREAD

**Issue by benjamingr** [jsdom/jsdom#2231]
### Basic info:

Browsers expose `window.performance` (which JSDOM supports) as well as the `Performance` constructor through `window.Performance`. JSDOM doesn't expose `window.Performance`.

Some of our users at Sinon.JS (lolex) were [confused by this](https://github.com/sinonjs/lolex/issues/171#issuecomment-389611334) and it caused their tests to fail when we've added a reference to `window.Performance`.

 - Is this a deliberate decision on behalf of JSDOM? (If so, should we count on `Object.getPrototypeOf('performance').
 - If it is not a deliberate decision - It seems like exposing Performance from [here](https://github.com/jsdom/jsdom/blob/master/lib/jsdom/browser/Window.js#L155) shouldn't be too hard - what would be the correct way to do this on our behalf?

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const dom = new JSDOM('', {});
console.log(dom.window.Performance); // undefined
```

### How does similar code behave in browsers?

All the browsers we test that support `window.performance` also expose expose `window.Performance`.

**Comment by Zirro** [comment]
I can't reproduce this - the reproduction case logs `[Function: Performance]` for me. The interfaces are added here: https://github.com/jsdom/jsdom/blob/master/lib/jsdom/browser/Window.js#L67. Do you actually get `undefined` when you run it?

Looking at the comments in https://github.com/sinonjs/lolex/issues/171 - and https://github.com/sinonjs/lolex/issues/171#issuecomment-389359074 in particular - it seems like this may be an issue caused by globals from jsdom being copied to the Node.js `global`. We [advise against](https://github.com/jsdom/jsdom/wiki/Don't-stuff-jsdom-globals-onto-the-Node-global) doing so for this reason.

**Comment by benjamingr** [comment]
@Zirro so just to clarify - this is not caused by JSDom - it is caused by presumably some code that copies properties over to the Node global?

Got it. Definitely not something I think JSDom should solve on its end since it's not doing anything unexpected. I'll guard against it just in case from our side - thanks.

Also - it's interesting why it's hitting users (in particular). I got it by running a users' reproducing use case.

**Comment by benjamingr** [comment]
Also, going to close this since it doesn't appear to be on your end - if you disagree feel free to reopen. 

Thanks for the quick response :)
