### ISSUE TITLE
value instance of Array is false when value is passed from outside

### ISSUE THREAD

**Issue by roonyh** [jsdom/jsdom#2261]
### Basic info:

- **Node.js version: 8.11.2** 
- **jsdom version:11.4.0** 

### Minimal reproduction case

```js
const { JSDOM } = require('jsdom');

const dom = new JSDOM(`
<body>
  <script>window.test = value => {console.log(value instanceof Array)}</script>
</body>`, 
{ runScripts: "dangerously" }
);

dom.window.test([]);  // Prints false
```

### How does similar code behave in browsers?
It prints `true`
https://jsbin.com/xucixewafo/edit?html,console,output

**Comment by papandreou** [comment]
This is a consequence of jsdom using [vm contexts](https://nodejs.org/api/vm.html) to execute JavaScript on the page. Each `vm` context has its own copy of the globals, including `Array`, so that's why arrays created in your main JavaScript aren't instances of the `Array` constructor that is seen from inside the jsdom instance. Here's a similar example:

```js
const vm = require('vm');

const context = vm.createContext({});
const foreignArray = vm.runInContext('[]', context);

console.log(foreignArray instanceof Array); // false
```

However, the `foreignArray` is an instance of the `Array` constructor in the vm context:

```js
const foreignArrayConstructor = vm.runInContext('Array', context);
console.log(foreignArray instanceof foreignArrayConstructor); // true
```

This is similar to how frames and iframes work -- each one also has its own set of globals. That's why the older generation of web devs have discouraged the use of `instanceof Array`, as it breaks in cross-frame settings.

The best fix is to use `Array.isArray` instead:

```js
console.log(Array.isArray(foreignArray)); // true
```

**Comment by roonyh** [comment]
Thanks for the insight. Ended up doing this. Works for me as the value is a json object in my case.

```js
const { JSDOM } = require('jsdom');

const dom = new JSDOM(`
<body>
  <script>window.test = value => {
    const _value = JSON.parse(JSON.stringify(value));
    console.log(_value instanceof Array)}
  </script>
</body>`, 
{ runScripts: "dangerously" }
);

```

**Comment by TimothyGu** [comment]
That's why you always want to use `Array.isArray()` to test for arrays. Unfortunately the same check isn't available for most other objects.
