### ISSUE TITLE
Repeating querySelectorAll on DocumentFragment after modification causes runtime error

### ISSUE THREAD

**Issue by dxparker** [jsdom/jsdom#2290]
nwsapi throws the runtime error: `context[m] is not a function` when a call to `querySelectorAll` is repeated on a document fragment, after the fragment has been modified. Inside the `validate` function nwsapi is trying to invoke `getElementsByTagName` on the document fragment.

This problem is usually masked by jsdom returning the cached result from the original call to `querySelectorAll`. Modifying the fragment between calls clears the cache and exposes the issue.

### Basic info:

- **Node.js version:** 8.11.3 and 10.5.0 (node version does not matter)
- **jsdom version:** 11.11.0

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");
const dom = new JSDOM();
let document = dom.window.document;

let frag = document.createDocumentFragment();
frag.appendChild(document.createElement('div'));
frag.querySelectorAll('img');
// Modify fragment, then repeat querySelectorAll with same selector
frag.appendChild(document.createElement('div'));
frag.querySelectorAll('img');
```

**Comment by Zirro** [comment]
Thanks for the detailed report! @dperini, could you take a look at this issue?

**Comment by dperini** [comment]
YES ! I am going to check it out and be back with a new release asap.
At first sight and going by memory it seems that it should be:

    compat[m]( context, ident[i] )

instead of:

    context[m]( ident[i] )

Also, strange that several thousands of tests couldn't reveal the bug, we have many tests checking for modified DOM trees within `DocumentFragment` in both the older W3C tests and in newer WPT tests.

**Comment by dperini** [comment]
@dxparker 
Probably solved by: https://github.com/dperini/nwsapi/commit/bd1a84a58a
Needs testing and confirmation before 2.0.5 release.
Thank you for reporting the issue.

**Comment by dxparker** [comment]
Thanks for such a quick turn around @dperini.

Does anyone on this thread know when JSDOM will release with the updated `nwsapi` dependency? Didn't find any info on the release process/cadence. Just need to determine whether I should patch my copy of JSDOM or wait for an update from npm.

**Comment by Zirro** [comment]
Since nwsapi 2.0.5 is a minor release (only the last version number changed), new installations of jsdom will use that version automatically. For existing installations, it's usually enough to remove and reinstall jsdom through npm or yarn to get the latest subdependencies. (see [Semantic Versioning](https://www.sitepoint.com/semantic-versioning-why-you-should-using/))

**Comment by domenic** [comment]
This should be fixed; we require newer nwsapi versions out of the box now.

**Comment by domenic** [comment]
But, we should add tests before we close this. Tagging as such.
