### ISSUE TITLE
Polyfill of native class doesn't accepted by babel's _isNativeFunction function

### ISSUE THREAD

**Issue by ENvironmentSet** [jsdom/jsdom#2433]
### Basic info:

- **Node.js version: 10.13.0** 
- **jsdom version: 13** 

### Minimal reproduction case
let's say we are using babel and it's preset is `@babel/preset-env`.

when `CustomEvent` class is a native class by browser.
this code works well even we compile it with babel.

```js
class MockEvent extends CustomEvent {
  constructor(detail = {}) {
    super('mockEvent', {
      detail
    });
  }
}

const mockEvent = new MockEvent({ babel: true });
```

[compiled code by babel](http://jsfiddle.net/ENvironmentSet/d92nqarj/2/)

but, when `CustomEvent` class is polyfill of jsdom.
above code throws TypeError in below.

` TypeError: Failed to construct 'CustomEvent'. Please use the 'new' operator; this constructor cannot be called as a function.`

when babel calls `_wrapNativeSuper` with `CustomEvent`(a polyfill of jsdom), `_wrapNativeSuper` will check does given argument is native function by calling `_isNativeFunction` with given argument.
and, `_isNativeFunction` will check does  result of calling `Function.prototype.toString` with given function returns string that contains `'[native code]'` . 
but, as we know jsdom's `CustomEvent.toString()` doesn't. So babel will think `CustomEvent` is not a native class and will not wrap it.
this the reason why this error be thrown.

So.. how about to change every built-in function polyfill's `toString` method?
as I know, ECMAScript spec forces result of built-in function's `toString` method should be string that can't be parse as javascript code.
and.. I think built-in function polyfill should act like built-in function.

### How does similar code behave in browsers?

http://jsfiddle.net/ENvironmentSet/8o34tsan/1/

**Comment by domenic** [comment]
This would be an interesting and nice feature to have. Unfortunately it's not really possible in JavaScript. You mention a workaround, of overriding toString() on everything, but that's not very feasible. Think of how many functions jsdom has, including all the methods etc.

Instead, I have a proposal for the JS language to allow code to do this itself: https://github.com/domenic/proposal-function-prototype-tostring-censorship . I hope one day to get back to that and make it available. I'm not sure the committee will be much swayed by the argument "this is necessary to work around Babel's heuristics", but oh well.

I have two suggestions for your case:

1. Ask Babel to add a mode where it assumes certain files are "native code", and configure your project to treat jsdom that way.
2. Don't use Babel on your code at all, because jsdom runs in Node.js where nothing needs transpiling with Babel.

I'll leave this open to track the fact that it's something we'd like to fix, but I don't think there's any good way to fix it besides adding a new feature to the JavaScript language, which is a long-term project.

**Comment by ENvironmentSet** [comment]
Wow, I hope that proposal became standard. 

anyway, I have same problem in jest.
when I use jest with `--testEnvironment=jsdom`(also I use babel-jest to transpile ES6 module. can you suggest some solutions to me?

**Comment by domenic** [comment]
Sorry, I don't know much about Jest; it's probably best to ask their community about it.

**Comment by ENvironmentSet** [comment]
Thank you for kind awnser :)
