### ISSUE TITLE
Cannot read property '_nwsapiDontThrow' of undefined

### ISSUE THREAD

**Issue by JRasmusBm** [jsdom/jsdom#2481]
Hi, I am very grateful for the work that you do, and I really hope this bug(?) report is helpful. If there's any information I can provide to make the issue clearer please let me know.

I thought it would be easier for you to get the gist of what I'm trying to do in a small repository I made for the purpose. It can be found [here](https://github.com/JRasmusBm/showcase_issue_jsdom).

- **Node.js version:** Reproduced both in 8.9 and in latest docker version.
- **jsdom version:** 13.1.0

### Minimal reproduction case

See my repo [here](https://github.com/JRasmusBm/showcase_issue_jsdom).

### How does similar code behave in browsers?

See the following [jsbin](https://jsbin.com/baxezaf/1/edit?html,console,output) for an example of how it works in the browser.

**Comment by Zirro** [comment]
Thanks for the report! `window.getComputedStyle()` expects a specific element as the argument, but `document.getElementsByTagName("h1")` returns a HTMLCollection which contains the element instead. You could either change it to `document.getElementsByTagName("h1")[0]`, or `document.querySelector("h1")` which should allow your code to work as intended.

In our code, we should be throwing an error earlier when the first argument is not of the expected type rather than the internal error that currently appears.

**Comment by JRasmusBm** [comment]
Thank you for a quick and educative reply! :+1: 
I leave the issue open in favor of improved error handling, but your response resolved my concern. Have a great evening!
