### ISSUE TITLE
dynamic import of `canvas` causes bundling problems

### ISSUE THREAD

**Issue by NathanielHill** [jsdom/jsdom#2508]
Unfortunately, the dynamic import of `canvas` trips up some bundlers that are trying to include all requirements. Perhaps the dynamic import can be further obfuscated, so it's not discoverable via static analysis?

**All** relevant code is here: 

https://github.com/jsdom/jsdom/blob/16d3913eea0360c7757e75f7e266c3873c85b7dd/lib/jsdom/utils.js#L163-L177

The problem it's causing has an issue here:

https://github.com/zeit/ncc/issues/274

**Comment by domenic** [comment]
Sorry, but we target Node.js, not bundlers. If bundlers are unable to handle this but still claim to support Node.js code, then they have a bug, or need more configuration.

Closing as working-as-intended, but feel free to discuss in the closed thread with others who might have an idea on how to configure your bundler.

**Comment by NathanielHill** [comment]
@domenic No problem, I just wanted to see if there was any insight here and to make sure there is a cross-reference.

I'm really not sure how this would be solved for the `ncc` bundling problem since it cannot know the value of `canvasInstalled` at bundle/compile time.

However it does seem like this could be easily fixed by passing a variable to `require()` instead of a string.

Would you be open to a small change like that?

**Comment by NathanielHill** [comment]
I agree this is not a `jsdom` bug. But, as the JS ecosystem still has not converged on module and import syntax, it would be reasonable to try and make sure dynamic imports will play as nicely as possible.

**Comment by domenic** [comment]
No, sorry, the code is working well right now for our target platforms, so I'd rather not obfuscate it, or take on the burden of supporting platforms outside our matrix which someone could easily break again with a trivial refactoring.

**Comment by sebastienfilion** [comment]
I am writing this just in case someone else runs into this problem, this is how I fixed it for me:
Assuming that you're bundling with Webpack...
First, make sure that you have `node-gyp` and `node-pre-gyp` installed globally;
Then install `canvas` as a dev. dependency `npm install canvas --save-dev`;
Finally, add this to your Webpack configs:
```
externals: {
		canvas: "commonjs canvas" // Important (2)
	}
```

**Comment by NathanielHill** [comment]
@sebastienfilion Thanks, this is helpful for some people I'm sure. My reason for the issue is when you don't have this level of control of your build environment... for example in some CI/CD pipelines.

**Comment by akirk** [comment]
If you don't want to use canvas and need avoid the error message `Module not found: Error: Can't resolve 'canvas'` when bundling with Webpack (for example because of a CI), it worked for me to remap `canvas` to the `util` package like this in `webpack.config.js`:
```
externals: {
	canvas: "util"
}
```
Since [jsdom checks the Canvas object](https://github.com/jsdom/jsdom/blob/master/lib/jsdom/utils.js#L159) for `typeof Canvas.createCanvas === "function"` it will fail and thus not enable canvas support.

Webpack rewrites the `require("canvas")` to `require("util")` (actually something like `__webpack_require__(/*! canvas */ \"util\");`) which succeeds which in turn prevents the error message. Since the `util` function is part of node, it doesn't add to the weight of the bundle.
