### ISSUE TITLE
Possible MutationObserver issue

### ISSUE THREAD

**Issue by kschzt** [jsdom/jsdom#2509]
Hi, I am running A-Frame with a dummy THREE renderer in Node with jsdom (yes, it makes actual sense for us to run A-Frame server side) and after a lot of wondering about why it doesn't boot up, finally landed on this line:

https://github.com/jsdom/jsdom/blob/2898617587bf40a5705eb3692037fbf9b3631030/lib/jsdom/living/helpers/mutation-observers.js#L132

If I comment out the "microtask delay" ie. the Promise wrapper, and notify the observers immediately, A-Frame boots up correctly. I suspect this is also how browsers _actually_ do it.

This could well be a bug in A-Frame that relies on actual behavior in browsers and the jsdom MO behaves according to spec.

Thoughts?

**Comment by domenic** [comment]
Browsers definitely have a microtask delay; that's in the spec.

Can you provide a minimal example, following the issue template, which behaves differently in jsdom versus browsers? Since this issue doesn't follow the issue template, we have to close it, but I'm happy to reopen if you edit it to do so and then reply with a follow-up comment.
