### ISSUE TITLE
iframe.contentWindow.requestAnimationFrame is undefined (even with `pretendToBeVisual: true`)

### ISSUE THREAD

**Issue by pyrho** [jsdom/jsdom#2538]
### Basic info:

- **Node.js version:** 11.6.0
- **jsdom version:** 14.0.0

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const dom = new JSDOM(`<body><iframe id="i1"></iframe></body>`, { pretendToBeVisual: true });
const ifame1Window = dom.window.document.querySelector('#i1');

if (!dom.window.requestAnimationFrame) { 
    throw new Error('requestAnimationFrame should exist on window');
}

const iframe2 = dom.window.document.createElement('iframe');
iframe2.id = "i2"
dom.window.document.body.appendChild(iframe2);
const iframe2Window = iframe2.contentWindow;

if (!ifame1Window.requestAnimationFrame || !iframe2Window.requestAnimationFrame) { 
    throw new Error('requestAnimationFrame should exist on iframe.contentWindow');
}
```

JsBin: https://jsbin.com/qepirocara/1/edit?html,js,console
Link to spec: https://html.spec.whatwg.org/multipage/imagebitmap-and-animations.html#animation-frames

### ❤️  
Thank you for your hard work on this project !

**Comment by domenic** [comment]
https://github.com/jsdom/jsdom#pretending-to-be-a-visual-browser

**Comment by domenic** [comment]
Oh dang, I'm so sorry, I see you already included that.

**Comment by pyrho** [comment]
I should have mentioned it in the case as it's an easy mistake to make, fixed.

**Comment by pyrho** [comment]
If you give me some pointers I'll gladly submit a PR for this.

**Comment by Zirro** [comment]
Thanks for reporting this bug! The problem appears to be that we're not passing along the `pretendToBeVisual` option as we create the new window for the `<iframe>`. To do so, this list needs another entry that copies over the `pretendToBeVisual` option from the original window: https://github.com/jsdom/jsdom/blob/master/lib/jsdom/living/nodes/HTMLFrameElement-impl.js#L111

A PR would be very appreciated! Just to save you a bit of debugging, I'll also mention that your original test case has a small issue where `ifame1Window` is set to the `<iframe>` element rather than the element's `contentWindow`.
