### ISSUE TITLE
Selection can only handle one Range at a time.

### ISSUE THREAD

**Issue by jonnyarnold** [jsdom/jsdom#2815]
### Basic info:

- **Node.js version:** v13.3.0 
- **jsdom version:** v16.0.0 

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom")

const dom = new JSDOM(`<p>Hello</p>`, {})
const bodyText = dom.window.document.querySelector("p").firstChild

const hRange = dom.window.document.createRange()
hRange.setStart(bodyText, 0)
hRange.setEnd(bodyText, 1)

const oRange = dom.window.document.createRange()
oRange.setStart(bodyText, 4)
oRange.setEnd(bodyText, 5)

const selection = dom.window.getSelection()
selection.addRange(hRange)
selection.addRange(oRange)
assert(selection.rangeCount === 2)
```

### How does similar code behave in browsers?

`rangeCount` is 2 in all browsers, but 1 in JSDOM.

### Notes

[The JSDOM implementation of `Selection`](https://github.com/jsdom/jsdom/blob/30bedcf62e03be5f64f1271e9753b5218c7ed9f1/lib/jsdom/living/selection/Selection-impl.js#L326) seems to assume only one range at a time. It looks like this will need updating to deal with an array of ranges instead.

**Comment by pmdartus** [comment]
From on the [Selection specification](https://w3c.github.io/selection-api/#dom-selection-rangecount):

>rangeCount
The attribute must return 0 if the context object is empty, and must return 1 otherwise.

When running the above code ([jsfiddle](https://jsfiddle.net/n5bq8932/)) on different browsers, Firefox is the only browser not respecting the specification. Here is the bug tracking this issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1149491
