### ISSUE TITLE
[BUG] Failed to execute 'dispatchEvent' on 'EventTarget': parameter 1 is not of type 'Event'

### ISSUE THREAD

**Issue by SoloJiang** [jsdom/jsdom#2949]
### Basic info:

- **Node.js version:**  10.16.0
- **jsdom version:**  16.2.2

When I dispatch an event on a node, it throws an error:
![image](https://user-images.githubusercontent.com/14757289/79643047-98cee580-81d3-11ea-930e-4e264b75c35d.png)
However, I debugged it, and then I find there use `Object.hasOwnProperty` check `Symbol`
key:
![image](https://user-images.githubusercontent.com/14757289/79643299-edbf2b80-81d4-11ea-8555-a019084af0c0.png)

![image](https://user-images.githubusercontent.com/14757289/79643096-d92e6380-81d3-11ea-8f1e-a1e120814e9a.png)
It's the unpkg link: https://unpkg.com/browse/jsdom@16.2.2/lib/jsdom/living/generated/Event.js

In my view, `Symbol` key can be checked by `hasOwnProperty` when used as `Symbol.for('impl')`

**Comment by domenic** [comment]
This does not follow the issue template, so we cannot help debug this. Please edit the original post to follow the issue template and add a comment, then we can reopen.

**Comment by asimontsev** [comment]
I have encountered exactly the same problem (but with another object - FormData). I was about to submit an issue, but while preparing a repro, I have figure out what is wrong. It is more a Jest-related usage issue, but I thought that it would be a good idea to post a solution for someone who reaches out to this issue through Google (like I did).

**Problem description**

I was setting up the mock document as follows: 

``` ts
            docSpy.mockImplementation(() => new JSDOM(`
                <!DOCTYPE html>
                <html>
                    <body>
                        ${testForm}
                    </body>
                </html>
            `).window.document)
```

I had a code like: 

``` ts
const form = document.querySelector<HTMLFormElement>("form[action='/cart/add']");
const formData = new FormData(form);
```
It was throwing "TypeError: Failed to construct 'FormData': parameter 1 is not of type 'HTMLFormElement'.". Like for the topic-started, during the debug, I saw that it failed because `utils.hasOwn(obj, implSymbol)` returned false despite of the fact that it did have this Symbol.

**Cause**

Eventually, I have figured out that I have mocked the document, but did not do it for `window`. Apparently, when I try to do `new FormData(...)` (which is the same as `window.FormData`), it works with a different instance of `window` from another instance of JSDOM. Therefore, the `Symbol("impl")` are no the same. 

**Solution**

I have solved this problem by changing my mock code to refer the same JSDOM instance: 

``` ts
            const testDom = new JSDOM(`
                <!DOCTYPE html>
                <html>
                    <body>
                        ${testForm}
                    </body>
                </html>
            `);
            windowSpy.mockImplementation(() => testDom.window)
            docSpy.mockImplementation(() => testDom.window.document)
```
Now FormData recognizes the form received 

Of course, you need to setup/teardown windowSpy/docSpy with `jest.spyOn()`/`mockRestore()` (I have omitted it since it is not relevant to jsdom).

Hope this helps anyone struggling with the same problem.
