### ISSUE TITLE
event.stopPropogation() behaviour in the target phase

### ISSUE THREAD

**Issue by alexreardon** [jsdom/jsdom#3070]
### Background

When adding an event listener to an `EventTarget` (eg a `Element`), you can control whether the event listener will be added in the capture phase or bubble phase:

```js
// adding in the capture phase
element.addEventListener('click', listener, { capture: true });

// adding in the bubble phase
element.addEventListener('click', listener, { capture: false });
```

When `element` is the `target` of an event both of the above event listeners are called in the `target` phase. The `capture` event listeners are always called before `bubble` phase event listeners - even though technically they are both being hit in the same event phase (the `target` phase)

### Issue: `event.stopPropogation()`

> "`event.stopPropogation()`: When dispatched in a tree, invoking this method prevents event from reaching any objects other than the current object."
> ~ [DOM Living Standard — Last Updated 27 October 2020](https://dom.spec.whatwg.org/#stop-propagation-flag)

When an event listener calls `event.preventDefault()` in a `capture` phase listener, which is being called in the `target` phase, should `bubble` listeners be called? 

Reading the spec, my thinking is that yes, they should be called as the event is still within the "current object". Chrome and Firefox agree with that perspective: the `capture` phase listeners are called. However, Safari has gone the other way and `capture` phase listeners are not called (although that might be a bug)

### Basic info:

- **Node.js version:** 12.16.3
- **jsdom version:** 16.4.0

### Minimal reproduction case

```js
const { JSDOM } = require('jsdom');

const dom = new JSDOM(`
  <!DOCTYPE html>
  <html lang="en">
    <head>
    </head>
    <body>
      <button id="button">click me</button>
    </body>
  </html>
`);

const button = dom.window.document.querySelector('#button');

button.addEventListener(
  'click',
  function inCapture(event) {
    event.stopPropagation();
    console.log(
      'capture listener',
      event.eventPhase === event.AT_TARGET ? 'in target phase' : 'in other phase',
    );
  },
  { capture: true },
);
button.addEventListener(
  'click',
  function inBubble(event) {
    console.log(
      'bubble listener',
      event.eventPhase === event.AT_TARGET ? 'in target phase' : 'in other phase',
    );
  },
  { capture: false },
);

button.dispatchEvent(new dom.window.MouseEvent('click', { bubbles: true, cancelable: true }));
```

### How does similar code behave in browsers?

- Chrome and firefox: event is stopped after the capture + bubble listeners in the target phase are complete (this is not what jsdom is doing right now)
- Safari: event is stopped after capture listeners (but I think this is a bug as it does not line up with the wording in the spec (this is what jsdom is doing)

[Code sandbox](https://codesandbox.io/s/stop-propogation-in-target-phase-x79si?file=/src/index.ts)

**Comment by domenic** [comment]
This issue does not follow the issue template, and seems to involve external libraries (jest?), so we have to close it. Please feel free to edit it to follow the template and add a comment here and we can consider reopening.

**Comment by alexreardon** [comment]
Hi @domenic, I have updated this issue to follow the issue template

**Comment by alexreardon** [comment]
I also removed jest from all the to simplify things

**Comment by domenic** [comment]
Perfect, thank you!

**Comment by domenic** [comment]
So first of all, if you've found a browser interoperability problem, especially one where 2/3 browsers agree, then you've definitely found something significant. Thanks for this work.

We have three situations this could be in:

- jsdom/Safari are following the spec, and the spec is good despite only matching 1/3 browsers: Chrome and Firefox will fix their bugs
- jsdom/Safari are following the spec, but when we go ask the spec authors, we find out that they'd prefer to match 2/3 browsers: we will update the spec, and then jsdom and Safari will fix their bugs
- Chrome/Firefox are following the spec: we should double-check with the spec authors, but probably jsdom and Safari will fix their bugs

Now, let's try to figure out who the spec agrees with. By my reading, the only place the stop propagation flag is consulted is in https://dom.spec.whatwg.org/#concept-event-listener-invoke step 4:

> If event’s stop propagation flag is set, then return. 

That "invoke" algorithm, in turn, is called twice: once for capturing, and once for bubbling.

So by my reading, Safari/jsdom follow the spec, because they bail out early from the second "invoke" call, without actually invoking any listeners.

This stuff is complicated, and I might be missing something, so could you double-check my logic? If I'm right, then our next step is to go file an issue on https://github.com/whatwg/dom , and see whether the spec authors believe the spec is good as-is, or if they'd prefer the spec to match 2/3 browsers.

**Comment by alexreardon** [comment]
> For each struct in event’s path, in reverse order:
>   1. If struct’s shadow-adjusted target is non-null, then set event’s `eventPhase` attribute to `AT_TARGET`.

What if an event listener calls preventDefault() here? Technically 'invoke' is not called yet. Oh, I'm guessing that 1 or 2 is run, and then 3 is always run

>  2. Otherwise, set event’s `eventPhase` attribute to `CAPTURING_PHASE`.
>  3. **Invoke** with struct, event, "capturing", and legacyOutputDidListenersThrowFlag if given.


>  For each struct in event’s path:
>   1. If struct’s shadow-adjusted target is non-null, then set event’s `eventPhase` attribute to `AT_TARGET`.
>   2. Otherwise:
>     1. If event’s `bubbles` attribute is false, then continue.
>     2. Set event’s `eventPhase` attribute to `BUBBLING_PHASE`.
>   3. Invoke with struct, event, "bubbling", and legacyOutputDidListenersThrowFlag if given.

So on my reading there are two seperate *invoke* steps, one for the capture phase, and one for the bubble phase. In which case, it seems like the Safari / jsdom behaviour is correct.

But I am not confident in that answer at all. I would be great to get the input from a spec author

I am also unsure about this:

> "`event.stopPropogation()`: When dispatched in a tree, invoking this method prevents event from reaching any objects other than the current object."
> ~ [DOM Living Standard — Last Updated 27 October 2020](https://dom.spec.whatwg.org/#stop-propagation-flag)

Based on my reading of that, it seems like the behaviour in Chrome / Firefox is the correct approach (as we are still on the same object)

**Comment by domenic** [comment]
> Based on my reading of that, it seems like the behaviour in Chrome / Firefox is the correct approach (as we are still on the same object)

That's just a summary for web developers, and not the actual spec text that implementations are meant to follow. It doesn't capture all of the subtleties. But, maybe it needs to be updated... or maybe it reflects the original intent, and the spec text is wrong.

I'll file the whatwg/dom issue now!

**Comment by alexreardon** [comment]
If we exclude this:

> "`event.stopPropogation()`: When dispatched in a tree, invoking this method prevents event from reaching any objects other than the current object."
> ~ [DOM Living Standard — Last Updated 27 October 2020](https://dom.spec.whatwg.org/#stop-propagation-flag)

Does my take on the https://dom.spec.whatwg.org/#dispatching-events flow sound right to you?

The thing that is throwing me, is that `event.eventPhase` has the possible values:

- `Event.NONE`: `0`
- `Event.CAPTURING_PHASE`: `1`
- `Event.AT_TARGET`: `2`
- `Event.BUBBLING_PHASE`: `3`

Which to me implied that `AT_TARGET` was a separate phase. But my reading of https://dom.spec.whatwg.org/#dispatching-events makes me think that `AT_TARGET` is actual a modifier to the `target` during the capture or bubble phase

**Comment by alexreardon** [comment]
But this document explicitly states there are three phases: https://www.w3.org/TR/uievents/

<img width="660" alt="Screen Shot 2020-11-06 at 8 38 44 am" src="https://user-images.githubusercontent.com/2182637/98299278-8e5b2880-200b-11eb-9d67-9c4b198ed2e3.png">

<img width="300" alt="Screen Shot 2020-11-06 at 8 37 13 am" src="https://user-images.githubusercontent.com/2182637/98299169-5f44b700-200b-11eb-8354-b7aa3df19e47.png">

If the intention is that there are three separate phases, then **invoke** gets more interesting

> "To invoke, given a struct, event, **phase**, and an optional legacyOutputDidListenersThrowFlag, run these steps:"
> https://dom.spec.whatwg.org/#concept-event-listener-invoke

Because to me, I think that means that a `stopPropogation()` in the `target` phase _should_ allow all event listeners in that phase to be called (regardless of whether they are bubble or capture vent listeners)

**Comment by domenic** [comment]
This is getting pretty deep into the spec territory, and I'm not sure if I'll have time to walk through everything. But yes, your take in https://github.com/jsdom/jsdom/issues/3070#issuecomment-722038767 seems right and matches my reading.

My best advice is to follow the algorithms. So if you want to know when AT_TARGET is set, you can visit https://dom.spec.whatwg.org/#dom-event-at_target, and click on "AT_TARGET", and it will show you all the places it's referenced. You can then see that it's set in two places:

- https://dom.spec.whatwg.org/#ref-for-dom-event-at_target%E2%91%A3
- https://dom.spec.whatwg.org/#ref-for-dom-event-at_target%E2%91%A4

Deciphering the full implications will require more similar back-tracking steps; e.g., you'd need to understand what "shadow-adjusted target" is and when it is set to non-null. But even this initial step can make it clear that AT_TARGET is an alternative value to CAPTURING_PHASE and BUBBLING_PHASE.

Similarly, if you want to find out what values are passed as the third (_phase_) argument to "invoke", you can click "invoke" at https://dom.spec.whatwg.org/#concept-event-listener-invoke and find the two call sites:

- https://dom.spec.whatwg.org/#ref-for-concept-event-listener-invoke
- https://dom.spec.whatwg.org/#ref-for-concept-event-listener-invoke%E2%91%A0

As you can see, it is only ever passed "capturing" and "bubbling".

The UI Events document is not as helpful, because it doesn't have algorithms. Non-algorithmic sections of specs are generally trying to summarize the algorithmic parts that are implemented in browsers. But, they are often simplified, or use different terminology, or cause other mismatches. E.g. the "phase" UI Events is talking about is not related to the third (_phase_) argument to "invoke".

As such, they can be a useful starting point, but ultimately you need to check the algorithms to find the correct behavior, not the summary text. Ideally the summary text would match the algorithms, but sometimes it fails to do so: either because it wasn't updated when the algorithms were updated, or because it was written by someone who isn't as familiar with the algorithms, or because it's trying to explain things at a higher level without going into all the details the algorithms do. (If it went into the exact same amount of detail, then it'd be just as complicated as the algorithms, and so it'd be pointless to have it in the spec at all.)

**Comment by domenic** [comment]
Looks like Chrome and Firefox will be fixed to match jsdom, so I'll close this :)
