### ISSUE TITLE
 Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by jony89** [jsdom/jsdom#3072]
### Basic info:

- **Node.js version:** v12.13.1
- **jsdom version:**1 6.4.0

npm version : 7.0.8

"jest": "26.0.1",

### Minimal reproduction case

```js
import { JSDOM } from 'jsdom';
```

I get the following error : 

```
 FAIL  src/services/CuesManager.test.ts
  ● Test suite failed to run

    TypeError: Cannot convert undefined or null to object
        at Function.getPrototypeOf (<anonymous>)

      1 | // eslint-disable-next-line import/no-extraneous-dependencies
    > 2 | import { JSDOM } from 'jsdom';
        | ^

      5 | 

      at Object.<anonymous> (../../node_modules/whatwg-url/dist/utils.js:48:39)
      at Object.<anonymous> (../../node_modules/whatwg-url/dist/URL.js:4:15)
      at Object.<anonymous> (../../node_modules/whatwg-url/webidl2js-wrapper.js:3:13)
      at Object.<anonymous> (../../node_modules/whatwg-url/index.js:3:7

```

This is probably related to npm7 ?

**Comment by domenic** [comment]
This seems to involve third-party tools like jest and TypeScript, so we can't really help you debug. Please follow the issue template and produce a minimal reproduction case that is a `.js` file which you can run with `node test.js`.

If you can do so, please comment on this issue and we'll reopen it. Until then we have to assume it's not a jsdom bug.

**Comment by rohitkrishna094** [comment]
@jony89 Hi, I am having a similar issue as well and there is not much literature online either. I was able to find only one other [stackoverflow question](https://stackoverflow.com/questions/64258790/react-project-works-fine-in-local-but-fails-in-production-build).

Were you able to resolve this? I am using react and looks like jsdom is a transitive dependency. When I run `npm ls jsdom`, this is what I get, not sure how to proceed. `npm start` works fine, but `npm build` is not working which is weird.

```
└─┬ react-scripts@4.0.3
  └─┬ jest-circus@26.6.0
    └─┬ jest-runner@26.6.3
      └─┬ jest-config@26.6.3
        └─┬ jest-environment-jsdom@26.6.2
          └── jsdom@16.4.0
```

**Comment by stevenleeg** [comment]
For anybody who is searching for this error realizing that nobody seems to have solved anything, perhaps I can help you out. I was running into this issue on a project that depended on jsdom, but used webpack to compile a bundle that would later be run on node v20.8.1.

I was stuck for a while before finally giving in and inspecting the output of webpack's compilation, finding this chunk of code where the error was occuring:

```
const AsyncIteratorPrototype = Object.getPrototypeOf(Object.getPrototypeOf(function() {
  return __asyncGenerator(this, null, function* () {
  });
}).prototype);
```

This was particularly strange since the source-mapped error was:

```
webpack://d3-renderer/node_modules/jsdom/lib/jsdom/living/generated/utils.js:34
const AsyncIteratorPrototype = Object.getPrototypeOf(Object.getPrototypeOf(async function* () {}).prototype);
                                      ^


TypeError: Cannot convert undefined or null to object
    at Function.getPrototypeOf (<anonymous>)
```

Looking at the [esbuild docs](https://esbuild.github.io/content-types/#javascript) I noticed that async generators are polyfilled before `es2018`, while our `webpack.config.js` was configured to transpile to `es2015`. Changing this option to `esnext` solved the issue, as the incompatible polyfill you see above is removed from the bundled output, allowing everything to work as you'd expect again.

Hopefully this helps somebody down the road!

**Comment by AntonPolyakin** [comment]
I don't know why, and I don't know how. But this helped me ✔️:

```
const __non_webpack_require__ = eval('require');
const { JSDOM } = __non_webpack_require__('jsdom'); 
```
