### ISSUE TITLE
SubmitEvent.submitter is undefined when a click submits a form

### ISSUE THREAD

**Issue by eps1lon** [jsdom/jsdom#3117]
### Basic info:

- **Node.js version:** 10.23.3
- **jsdom version:** 16.14.0

### Minimal reproduction case

Originally reported in https://github.com/testing-library/react-testing-library/issues/870

https://runkit.com/eps1lon/6024f498a573fe0019c227ca

```js
const {JSDOM} = require('jsdom');

const { window } = new JSDOM(`
      <form>
        <p>
          <input type="firstname" value="Michael" readOnly>
        </p>
        <p>
          <input type="lastname" value="Scott" readOnly>
        </p>
        <button type="submit" value="next" name="action">
          Next
        </button>
        <button type="submit" value="save" name="action">
          Save
        </button>
      </form>
`);
const { document, MouseEvent } = window;

const form = document.querySelector("form");
form.addEventListener("submit", (event) => {
  event.preventDefault();
  console.log(String(event.submitter))
});

const submitNext = form.querySelector('button[type="submit"]');
submitNext.dispatchEvent(new MouseEvent('click'))
```
Logs:
```
"undefined"
```

### How does similar code behave in browsers?
OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
Chrome: 88.0.4324.150

https://jsbin.com/mamocowata/edit?html,js,console,output

Logs:
```
"[object HTMLButtonElement]"
```

### Click events and default behavior

In case it's unclear whether a untrusted click event should even submit the form:

By spec user agents must run the activation behavior on click events:
> If the event target has associated activation behavior, the default action MUST be to execute that activation behavior (see § 3.5 Activation triggers and behavior).
-- (https://w3c.github.io/uievents/#event-type-click). 

Generally, untrusted events don't run default behavior. Click events are the only exception here:

> Most untrusted events will not trigger default actions, with the exception of the click event. This event always triggers the default action, even if the isTrusted attribute is false (this behavior is retained for backward-compatibility). All other untrusted events behave as if the preventDefault() method had been called on that event.

-- https://w3c.github.io/uievents/#trusted-events

**Comment by ChasinHues** [comment]
Does anyone know of a workaround that can be used in the meantime? 

The code I'm testing attempts to read React's `SyntheticBaseEvent`'s `nativeEvent.submitter`, however I haven't been able to test it so far because Jest's `nativeEvent` doesn't contain `submitter`. 

Similar to KCD's example [here](https://github.com/testing-library/dom-testing-library/issues/245), I tried to create a new event and add a getter for `submitter`, like so:
```ts
        // Create a new submit event.
        const event = new Event("submit", { bubbles: true, cancelable: false });
        // Get the HTMLElement that submits the form.
        const submitter = screen.getByRole("button", { name: "Save Draft" });
        // Add the submitter getter method to the event.
        Object.defineProperty(event, "submitter", {
            get: () => submitter,
        });
        const form = screen.getByRole("form");
        // Fire the submit event on the form.
        fireEvent(form, event);
```

But this doesn't appear to change the events `nativeEvent`. A `console.log` in the receiving components `onSubmit` outputs:
```
  console.log
    {
      context: SyntheticBaseEvent {
        _reactName: 'onSubmit',
        _targetInst: null,
        type: 'submit',
        nativeEvent: Event { isTrusted: [Getter] },
        target: HTMLFormElement {
          '__reactFiber$hqbzh7a2g1c': [FiberNode],
          '__reactProps$hqbzh7a2g1c': [Object]
        },
        currentTarget: null,
        eventPhase: 3,
        bubbles: true,
        cancelable: false,
        timeStamp: 1614137500143,
        defaultPrevented: true,
        isTrusted: false,
        isDefaultPrevented: [Function: functionThatReturnsTrue],
        isPropagationStopped: [Function: functionThatReturnsFalse]
      }
    }
```

**Comment by LeonBlade** [comment]
I know this is an old ticket, but I'm wondering if there are plans to address this or if anyone has a suggested workaround for this issue? Thank you.

**Comment by schang124** [comment]
It seems like this issue is re-generated on jsdom v19.
My test code does not trigger submit event when clicked on button[type="submit"].
Could anyone help me to fix this issue?

**Comment by simonshout** [comment]
Heya, chiming in late 2023 to report that this issue still exists on jsdom v20.
I have a similar set up where I have 2 submit buttons on a form and I differentiate them via name attribute.

When using testing-library to simulate user events with `user.click()` the submit event should look something like this:
```
{
  ...form element stuff
  target: "form element"
  nativeEvent: {
    submitter: {
      ...button element stuff
      name: 'submit button name'
    }
  }
}
```

But instead the nativeEvent is of Event type with just a isTrusted Getter and nothing else.
This all works in the browser when run and the contents of the event are all correct. This issue is only happening in tests.
