### ISSUE TITLE
how to specify origin/local IP?

### ISSUE THREAD

**Issue by tr4g** [jsdom/jsdom#3218]
Hi, I can't find in the docs how to specify which of my server's IP addresses to use in a request, the way I can achieve with cURL, Wget or request.

**Comment by TimothyGu** [comment]
fromURL is intended as a simple shorthand. If you want more control over how HTTP request is being done, use your preferred library and use the normal `JSDOM` constructor with the [`url` option](https://github.com/jsdom/jsdom#simple-options).

**Comment by tr4g** [comment]
@TimothyGu would you be so kind to answer my question and tell me how exactly can I specify the IP i want to make the request from? thanks!

**Comment by TimothyGu** [comment]
@tr4g Consult the Node.js documentation on the [http](https://nodejs.org/docs/latest/api/http.html#http_http_request_options_callback) module. In particular, you might want to provide a custom `lookup` function that returns the desired IP address for your domain instead of using the default [`dns.lookup`](https://nodejs.org/docs/latest/api/dns.html#dns_dns_lookup_hostname_options_callback).

Once you have downloaded the entire HTTP response into a Buffer, you can initialize JSDOM using `new JSDOM(buf, { url: originalURL })` as I described previously.
