### ISSUE TITLE
Any chance we can this to work with Deno?

### ISSUE THREAD

**Issue by ralyodio** [jsdom/jsdom#3279]
I'm fine using esm.sh site to load it, but right now it doesn't exist there.

The deno_dom library does not work with moz-readability

**Comment by domenic** [comment]
I'm not interested in spending the effort to support another runtime myself, but you're welcome to create a fork!

**Comment by ralyodio** [comment]
If you can make it so https://esm.sh/jsdom works that's all you would need to do. I think it just needs to export commonjs

**Comment by domenic** [comment]
jsdom already exports CommonJS.

**Comment by ralyodio** [comment]
Hmmm...this is the error I get. I assume it has something to do with requiring node process.

```
error: Import 'https://cdn.esm.sh/error.js?type=unsupported-nodejs-builtin-module&name=child_process&importer=jsdom' failed: 500 Internal Server Error
    at https://cdn.esm.sh/v57/jsdom@18.0.1/es2021/jsdom.js:2:1022
```

**Comment by jespertheend** [comment]
It seems to work fine for me:
```js
// jsdomtest.js

import {JSDOM} from "https://cdn.esm.sh/jsdom";

const dom = new JSDOM();
const el = dom.window.document.createElement("div");
console.log(el);
```

Then run with
```
deno run --unstable jsdomtest.js
```
which logs
```
HTMLDivElement {}
```

**Comment by nyancodeid** [comment]
A few days ago I needed `jsdom` on my deno app, but this is very difficult because we can't use it directly using skypack/pika. Simple code might work, but you might get an error when there is an img element in the DOM.

So I made a copy version of `jsdom` and published it under the name `jsdom-deno` on [NPM](https://www.npmjs.com/package/jsdom-deno) to make it work (just remove `canvas` package). You can use it with an example like this.

```ts
import { JSDOM } from "https://jspm.dev/npm:jsdom-deno@19.0.1"

const dom = new JSDOM(`<!DOCTYPE html><p>Hello world <img src="https://example.com/logo.svg" /></p>`);

console.log(dom.window.document.querySelector("p").textContent); // "Hello world"
console.log(dom.window.document.querySelector("img").getAttribute('src')); // "https://example.com/logo.svg"
```
output
```bash
Hello world
https://example.com/logo.svg
```
if we import jsdom using module serve from `https://cdn.esm.sh/jsdom` we might get this error with the code as example above 

```bash
error: Uncaught TypeError: aV.Image is not a constructor
```

**Comment by YuukiToriyama** [comment]
This works! 
```typescript
import { JSDOM } from 'npm:jsdom'
```
