### ISSUE TITLE
CVE-2021-20066: Security vulnerability

### ISSUE THREAD

**Issue by Chrisjack56** [jsdom/jsdom#3304]
JSDom improperly allows the loading of local resources, which allows for local files to be manipulated by a malicious web page when script execution is enabled. More information can be found at the attached link.

https://nvd.nist.gov/vuln/detail/CVE-2021-20066

**Comment by Sebmaster** [comment]
Don't allow script execution on untrusted input, we cannot make it safe. Definitely not with significant work, maybe ever.

The suggestion of disabling loading of local files is not nearly sufficient to block even an only slightly determined attacker.

**Comment by domenic** [comment]
Yeah, this CVE is created by a company that basically makes their living filing bogus CVEs against projects by ignoring their threat models. We tried reaching out to NIST to get the CVE marked as "disputed", but they said that the CVE in question is managed by the company that filed it and we'd have to get them to update it. And of course that company ignored our request to do so since it's not in their financial interest.

Overall it seems like jsdom is experiencing a microcosm of what SQLite has already: https://www.sqlite.org/cves.html
