### ISSUE TITLE
Webpack builds fail on 20.0.1 with `Can't resolve 'perf_hooks'`

### ISSUE THREAD

**Issue by Slapbox** [jsdom/jsdom#3446]
### Basic info:

- **Node.js version:** 16.17.0
- **jsdom version:** 20.0.1

### Error

```
ERROR in ./node_modules/jsdom/lib/jsdom/utils.js 5:18-39
Module not found: Error: Can't resolve 'perf_hooks' in '/home/me/Documents/project/node_modules/jsdom/lib/jsdom'
 @ ./node_modules/jsdom/lib/jsdom/browser/Window.js 7:39-58
 @ ./node_modules/jsdom/lib/api.js 13:25-61
 @ ./packages/shared/project-worker-stuff/src/worker.js 7:0-26 23:8-19
 ```
 
It works fine for jsdom@20.0.0.

### Minimal reproduction case

Unknown.

### Additional info

Very weird since the relevant file hasn't changed in months: https://github.com/jsdom/jsdom/blob/master/lib/jsdom/utils.js

**Comment by domenic** [comment]
We don't know anything about the webpack project, so this isn't a good place to file such an issue.

**Comment by Slapbox** [comment]
I'm just saying that `20.0.0` builds fine... Patch level releases shouldn't break things like this generally speaking. You don't have to address it, but I don't know where you'd expect me to file an issue besides with the authors of the faulting dependency...

**Comment by DarrenCook** [comment]
Thanks, this is happening to me too. I've gone back to jsdom@20.0.0 and that error goes away.


Aside: in its place I get two errors, one in ./node_modules/jsdom/lib/jsdom/browser/parser/html.js and the other in ./node_modules/parse5/dist/index.js.
I've tried going back to 19.0.0, and now no webpack complaints, but I get a runtime error.

I've just brought jsdom into this project, so it is quite possible these other errors are because I'm doing something wrong. I will keep working on it.
But at least I can confirm that the 20.0.1 looks to have been built incorrectly (given "perf_tools", perhaps some developer-only code has accidentally got left in?).

**Comment by ath0mas** [comment]
Just got same error.
Resolved by adding `perf_hooks` to [resolve.fallback](https://webpack.js.org/configuration/resolve/#resolvefallback) in webpack config.

**Comment by Slapbox** [comment]
Great tip! Thanks @ath0mas!

**Comment by nturinski** [comment]
> Just got same error. Resolved by adding `perf_hooks` to [resolve.fallback](https://webpack.js.org/configuration/resolve/#resolvefallback) in webpack config.

What did you resolve it to? Just `false`?

**Comment by ath0mas** [comment]
> > Just got same error. Resolved by adding `perf_hooks` to [resolve.fallback](https://webpack.js.org/configuration/resolve/#resolvefallback) in webpack config.
> 
> What did you resolve it to? Just `false`?

In my case, yes. But you may choose to `require` a polyfill or so if you need it.
