### ISSUE TITLE
Cannot find module './xhr-sync-worker.js' Error

### ISSUE THREAD

**Issue by jesney-johny** [jsdom/jsdom#3511]
### Basic info:

- **Node.js version:** 14.18.0
- **jsdom version:** 19.0.0

### Minimal reproduction case

JSDOM is one of the dependencies of adobe/acc-js-sdk package. While deploying the lambda in local there is an error

```
ERROR	Uncaught Exception 	{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module './xhr-sync-worker.js'\nRequire stack:\n- /var/task/index.js\n- /var/runtime/index.mjs",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module './xhr-sync-worker.js'",
        "Require stack:",
        "- /var/task/index.js",
        "- /var/runtime/index.mjs",
        "    at _loadUserApp (file:///var/runtime/index.mjs:1000:17)",
        "    at async Object.UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1035:21)",
        "    at async start (file:///var/runtime/index.mjs:1200:23)",
        "    at async file:///var/runtime/index.mjs:1206:1"
    ]
}
```
Only way I could fix it by updating

const syncWorkerFile = require.resolve ? require.resolve("./xhr-sync-worker.js")

at location node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:31 by

const syncWorkerFile = "${require.resolve('jsdom/lib/jsdom/living/xhr/xhr-sync-worker.js')}";

This works only in local.

**Comment by domenic** [comment]
This issue doesn't follow the issue template in containing a minimal reproduction case, so it is being closed.

**Comment by siseko** [comment]
@jesney-johny Suffered with this as well. I'm running jsdom in a Netlify function not sure about your setup. Hopefully this could help someone else.

My solution was adding below in the netlify.toml

```[functions]
  external_node_modules = ["jsdom"]
```
  
Interestingly, [going back to using commonjs modules](https://www.netlify.com/blog/intro-to-serverless-functions/#:~:text=Replace%20the%20CommonJS%20syntax%3A) also resolves this issue.

The crux of the issue though is in [this](https://stackoverflow.com/a/70171666) stackoverflow answer. Changing that require.resolve inside your jsdom node_modules to an absolute url resolves it. Obviously not a sustainable solution.

**Comment by up1-io** [comment]
I get the same error, on the execution of a Lambda function (deployed with CDK). 

Does anyone have a solution/workaround for this problem?

**Comment by magnusdr** [comment]
This is caused by how `xhr-sync-worker.js` is loaded [as seen in `lib/jsdom/living/xhr/XMLHttpRequest-impl.js`](https://github.com/jsdom/jsdom/blob/8e31507f3bb32c1face73df9e164f858feb5f2fa/lib/jsdom/living/xhr/XMLHttpRequest-impl.js#L31C7-L31C21).

```js
const syncWorkerFile = require.resolve ? require.resolve("./xhr-sync-worker.js") : null;
```

This makes it impossible for a bundler to include the file, essentially forcing it to be resolved at runtime.

I'm not sure why it is done this way. This particular way of resolving the module was introduced [8 years ago](https://github.com/jsdom/jsdom/commit/2c8933905e9b81436843fe8d429918876a277e54) when the `xmlhttprequest.js` (the predecessor of XMLHttpRequest-impl.js) was initially added to the repo.

As for now, I solved it by manually copying the `xhr-sync-worker.js` file into my `build` folder (this was a Remix project).

**Comment by DanKaplanSES** [comment]
If you are building a library and apps print this error message when they use it, use JSDOM as a peerDependency instead of a regular dependency.
