### ISSUE TITLE
ws dependency package vulnerability: CVE-2024-37890

### ISSUE THREAD

**Issue by ibakirov** [jsdom/jsdom#3736]
### Basic info:

- **Node.js version:** 18.20.3
- **jsdom version:** 24.1.0

### Minimal reproduction case

Please be informed that jsdom version 24.1.0 has ws package as dependency which is affected by [CVE-2024-37890](https://github.com/advisories/GHSA-3h5v-q93c-6h6q)

**Comment by domenic** [comment]
Since jsdom uses `^8.17.0`, 8.17.1 is automatically installed by all compliant package managers, so there is no problem.

**Comment by VanessaHenderson** [comment]
Just chucking a note in here that because jsdom 24.1.0's package-lock.json has ws version 8.17.0 in it, thats is what version gets installed when using jsdom 24.1.0. Unless a project has a version of ws that is being pulled in elsewhere that uses the 8.17.1, until a new version of jsdom is released projects will still be pulling in the vulnerable version of ws. Also by having ^8.17.0 it still allows people to be pulling in the vulnerable version.

So unfortunately there is actually a problem until the package is re-released with the package.json stating  ^8.17.1 and the package-lock.json saying the same thing, this library does contain and will continue to contain a vulnerable library.

**Comment by VanessaHenderson** [comment]
Ah, Apologies. I was basing it off what was happening in our projects. We are using 24.1.0 and even after removing our package-lock and reinstalling all of our dependencies, jsdom appears to be pulling in the vulnerable version of ws (jsdom is the only library using it). However I did just create a test project and installing jsdom only appears to have pulled in the correct version of ws. 

The point does still stand however that until the package.json is updated to for ^8.17.1 vulnerable versions of ws can still be distributed. 
Thanks for correcting my incorrect thinking on the package-lock though Sebmaster

**Comment by ibakirov** [comment]
I agree with @VanessaHenderson  and `^8.17.1` has to be defined in jsdom/package.json

**Comment by SchroederSteffen** [comment]
> I deleted both the `package-lock.json` file and the `node_modules` directory before running `npm install` to force an update to the new version of `ws`.

FYI: You could also use `npm i ws` & `npm rm ws` to update only this single transitive dependencies without having to re-install everything.
