### ISSUE TITLE
Cannot use "canvas": "3.0.0-rc2",

### ISSUE THREAD

**Issue by Andrekarma** [jsdom/jsdom#3743]
This is the error: Conflicting peer dependency: canvas@2.11.2

**Comment by domenic** [comment]
Yep, jsdom only works with canvas 2.x, that's why we declared that peerDependency!

When canvas v3 is released fully, we'll do the work necessary to integrate and upgrade.

**Comment by alumni** [comment]
@domenic `canvas` is getting close to a release (3.0.0-rc3 available now). In the meantime, the old version does not have prebuilds for Node 22 LTS (see https://github.com/Automattic/node-canvas/issues/2448), which makes it difficult to use in certain environments.

IIRC, forcing 3.0.0-rc2 was only causing issues with `jest-environment-jsdom` since some methods are now immutable.

**Comment by domenic** [comment]
Per discussion in https://github.com/jsdom/jsdom/pull/3795, I'm open to *only* supporting the v3.0.0-rc3. Someone just needs to create a version of that PR which passes CI.

**Comment by alumni** [comment]
Opened #3803 with added test configurations, CI seems to pass.

I think the test that was failing in the other PR was rather a flaky test, noticed it was failing in another PR as well. It didn't happen on my PR on any of the 3 commits, but very likely it could have.

**Comment by HarelM** [comment]
I think version 3 was just released recently, any chance to update this package and release it too?

**Comment by domenic** [comment]
Yep, just need another PR to update the peer dependencies.

**Comment by alumni** [comment]
3.0 is already allowed by the pattern `^3.0.0-rc3`

**Comment by HarelM** [comment]
Ahh great. I'll wait patiently to the release of a new version of jsdom. :-)
